### ISSUE TITLE
Can´t handle variables inclufing a comma in name

### ISSUE THREAD

**Issue by svenoone** [sfudeus/isg_exporter#94]
Crash when language is English on a ISG v12.2.3 + WPE-I 12H 230 Premium

```
panic: runtime error: index out of range [1] with length 0

goroutine 13 [running]:
main.normalizeValue({0xc0002fa759, 0x3})
        /build/scraping.go:151 +0x25d
main.parsePage.func1(0x0?, 0xc0005cd710)
        /build/scraping.go:110 +0xe5
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0005cca80, 0xc0004d9d00)
        /go/pkg/mod/github.com/!puerkito!bio/goquery@v1.9.1/iteration.go:10 +0x62
main.parsePage({0xc44709?, 0x0?}, 0xc0004d9ec8)
        /build/scraping.go:95 +0x114
main.gatherScrapingData()
        /build/scraping.go:73 +0x19b
main.gatherData()
        /build/main.go:178 +0x10a
main.main.func1()
        /build/main.go:96 +0x13
created by main.main in goroutine 1
        /build/main.go:94 +0x111
panic: runtime error: index out of range [1] with length 0
```

![image](https://github.com/sfudeus/isg_exporter/assets/47710373/72ae905c-30d1-4ff2-9cc3-ef3fdcfd7033)

[STIEBEL ELTRON Reglersteuerung_files.zip](https://github.com/sfudeus/isg_exporter/files/14733614/STIEBEL.ELTRON.Reglersteuerung_files.zip)

**Comment by svenoone** [comment]
German interface:
![image](https://github.com/sfudeus/isg_exporter/assets/47710373/7c459446-2ef2-4f28-9dea-1d3137d55b45)

**Comment by sfudeus** [comment]
thx for reporting, should be easy enough to fix.
